# Array Basics

## Dimensions in Array:
Numpy arrays could be of multiple dimensions.

In [6]:
def dimensions_in_arrays():
    a = np.array(42) # 0-D Arrays
    b = np.array([1, 2, 3, 4, 5]) # 1-D Arrays
    c = np.array([[1, 2, 3], [4, 5, 6]]) # 2-D Arrays
    d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) # 3-D arrays

    # Check Number of Dimensions?
    print(a.ndim)
    print(b.ndim)
    print(c.ndim)
    print(d.ndim)

    # Higher Dimensional Arrays
    e = np.array([1, 2, 3, 4], ndmin=5)
    print(e.ndim)
    print(e)

dimensions_in_arrays()


0
1
2
3
5
[[[[[1 2 3 4]]]]]


## Copy vs View

In [ ]:
def copy_vs_view():
    # Make a copy, change the original array, and display both arrays:
    arr = np.array([1, 2, 3, 4, 5])
    x = arr.copy()
    arr[0] = 42
    print(arr)
    print(x)
    print(id(arr), id(x), id(arr) == id(x), id(arr) is id(x))

    # Make a view, change the original array, and display both arrays:
    arr = np.array([1, 2, 3, 4, 5])
    x = arr.view()
    arr[0] = 42 # The view SHOULD be affected by the changes made to the original array.
    x[2] = 100 # The original array SHOULD be affected by the changes made to the view.
    print(arr)
    print(x)
    print(id(arr), id(x), id(arr) == id(x), id(arr) is id(x))

    # Print the value of the base attribute to check if an array owns it's data or not:
    # copies owns the data, and views does not own the data,
    # Every NumPy array has the attribute base that returns None if the array owns the data.
    # Otherwise, the base  attribute refers to the original object.
    arr = np.array([1, 2, 3, 4, 5])
    x = arr.copy()
    y = arr.view()
    print(x.base)
    print(y.base)
    print(id(arr), id(y.base))

copy_vs_view()

## Slicing

Numpy array slices are views to the original array.

### Slicing 1d array

In [7]:
def slice():
    # We pass slice instead of index like this: [start:end].
    # We can also define the step, like this: [start:end:step].
    # If we don't pass start its considered 0
    # If we don't pass end its considered length of array in that dimension
    # If we don't pass step its considered 1

    arr = np.array([1, 2, 3, 4, 5, 6, 7])
    print(arr[1:5])

    # Slice elements from index 4 to the end of the array:
    arr = np.array([1, 2, 3, 4, 5, 6, 7])
    print(arr[4:])

    # Slice elements from the beginning to index 4 (not included):
    arr = np.array([1, 2, 3, 4, 5, 6, 7])
    print(arr[:4])

    # Slice from the index 3 from the end to index 1 from the end:
    arr = np.array([1, 2, 3, 4, 5, 6, 7])
    print(arr[-3:-1]) # -3:-1 is converted to 4:6

    arr = np.array([1, 2, 3, 4, 5, 6, 7])
    print(arr[::2])

    #### IMPORTANT #####
    arr = np.array([1, 2, 3, 4, 5, 6, 7])
    print(arr[3:5:2]) # prints 4
    print(arr[3:1:2]) # prints nothing

slice()

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[1 3 5 7]
[4]
[]


### Slicing 2d array

Whenever a range is used on a dimension when slicing, the `.shape` of the sliced array will
be a tuple with some value (0 or non-zero) in place for the corresponding dimension.

i.e.

    a = np.array([[1, 2, 3], [10, 20, 30]])
    a[1, :].shape       # (3,) <= ranged is not used in the first dimension
    a[0:1, :].shape     # (1,3) <= ranged is used in the first dimension
    a[0:0, :].shape     # (0,3) <= ranged is used in the first dimension


In [14]:
def slice_2d():
    arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
    print(arr[:])
    print(arr[1])  # Other dimensions defaults to `:`, equivalent to arr[1,:]
    print(arr[1,:])
    print(arr[0, 1:4])

    # From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
    arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
    print(arr[0:2, 1:4])

    #### IMPORTANT #####
    arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
    print("\nIMPORTANT")
    print('arr[0:2, 1:4] =\n', arr[0:2, 1:4], arr[0:2, 1:4].shape)        # returns 2D array
    print('arr[1, 1:4] =', arr[1, 1:4], arr[1, 1:4].shape)                # returns 1D array
    print('arr[0:1, 1:4] =', arr[0:1, 1:4], arr[0:1, 1:4].shape)          # returns 2D array
    print('arr[0:0, 1:4] =', arr[0:0, 1:4], arr[0:0, 1:4].shape)          # returns 2D array, prints [] (0, 3)

slice_2d()

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 6  7  8  9 10]
[ 6  7  8  9 10]
[2 3 4]
[[2 3 4]
 [7 8 9]]

IMPORTANT
arr[0:2, 1:4] =
 [[2 3 4]
 [7 8 9]] (2, 3)
arr[1, 1:4] = [7 8 9] (3,)
arr[0:1, 1:4] = [[2 3 4]] (1, 3)
arr[0:0, 1:4] = [] (0, 3)


## Mutable Numpy Arrays

In [23]:
import numpy as np

a2 = a = np.array([2, 3, 4])
a[0] = 0  # numpy arrays are mutable
b = a + 1  # b is a new array object
print(id(b), id(a))

a = a[1:3]  # after the assignment `a` points to a view object of original a
print(id(b), id(a), id(a.base), id(a2))

a2 = a2 + 1  # after the assignment `a2` points to a new array object
print(id(b), id(a), id(a.base), id(a2))

print(a.base)
print(a)
print(a2)

2264826810800 2264821684720
2264826810800 2264821685968 2264821684720 2264821684720
2264826810800 2264821685968 2264821684720 2264821685392
[0 3 4]
[3 4]
[1 4 5]


# Misc Functions

## [ravel() vs flattern()](https://www.geeksforgeeks.org/differences-flatten-ravel-numpy/)

**a.ravel():**
- Return only reference/view of original array
- If you modify the array you would notice that the value of original array also changes.
- Ravel is faster than flatten() as it does not occupy any memory.
- Ravel is a library-level function.

**a.flatten():**
- Return copy of original array
- If you modify any value of this array value of original array is not affected.
- Flatten() is comparatively slower than ravel() as it occupies memory.
- Flatten is a method of an ndarray object.


# Set printing options

    numpy.set_printoptions(precision=None, 
                            threshold=None, 
                            edgeitems=None, 
                            linewidth=None, suppress=None, 
                            nanstr=None, 
                            infstr=None, 
                            formatter=None, 
                            sign=None, 
                            floatmode=None, 
                            *, 
                            legacy=None)[source]
 
These options determine the way floating point numbers, arrays and other NumPy objects are displayed.

https://numpy.org/doc/stable/reference/generated/numpy.set_printoptions.html

In [4]:
import numpy as np

Y = np.array([0.123, 0.234])
np.set_printoptions(formatter={'float': lambda x: "{0:0.2f}".format(x)})

# From this point onwards the newly set print options will be used 
print(Y[:])

# Reset back to defaults
np.set_printoptions(edgeitems=3, infstr='inf', linewidth=75, nanstr='nan', precision=8,
                    suppress=False, threshold=1000, formatter=None)
# or
# np.set_printoptions()

print(Y[:])

[0.12 0.23]
[0.123 0.234]


**Also to temporarily override options, use printoptions as a context manager:**

In [12]:
with np.printoptions(precision=2, suppress=True, threshold=5):
    print(np.linspace(0, 10, 10))
    
    
with np.printoptions(formatter={'all':lambda x: 'int: ' + str(-x)}):
    print(np.arange(3))

[ 0.    1.11  2.22 ...  7.78  8.89 10.  ]
[int: 0 int: -1 int: -2]
